version: '3'
services:
  broker:
    build: .
    container_name: broker
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - cassandra

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
  
