apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    app: message-broker
spec:
  type: NodePort
  selector:
    app: message-broker
  ports:
  - name: broker-grpc
    port: 8080
    targetPort: 8080
  - name: prometheus
    port: 8081
    targetPort: 8081
    
  