apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: message-broker
    run: cassandra
spec:
  selector:
    app: message-broker
    run: cassandra
  ports:
  - port: 9042
    targetPort: 9042
    
  