apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: message-broker
    run: redis
spec:
  selector:
    app: message-broker
    run: redis
  ports:
  - port: 6379
    targetPort: 6379
    
  